spring.application.name=payroll-api

# ????? Database ?????
spring.datasource.url=jdbc:postgresql://localhost:5432/payroll_db
spring.datasource.username=postgres
spring.datasource.password=151003

# ????? Redis ?????
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# ????? Email ?????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pathnimol0425@gmail.com
spring.mail.password=ppbpyqausjgqtgdl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ????? Sentry ?????
sentry.dsn=https://8c7f00695a5c4d55b6546379524774e1@o4509351203766272.ingest.us.sentry.io/4509351210123264
sentry.traces-sample-rate=1.0

aws.region=us-east-1
aws.s3.bucket=devconnectstrorage

# ????? Health ?????
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
